---
- name: Instalando MariaDB y otros módulos necesarios...
  apt:
        name:
                - mariadb-server
                - python3
                - python3-mysqldb
                - ufw
        state: present

- name: Habilitar UFW
  ufw:
    state: enabled

- name: Reiniciando MariaDB
  service:
          name: mariadb
          enabled: true
          state: restarted

- name: Usando mysql_secure_installation para establecer una contrseña de Root.
  shell: |
          echo -e "\nn\nY\n{{ db_root_pass }}\n{{ db_root_pass }}\nY\nn\nY\nY\n" | sudo mysql_secure_installation
  args:
   executable: /bin/bash

- name: Reiniciar mariadb
  service:
    name: mariadb
    enabled: true
    state: restarted

- name: Creando base de datos a raíz de variables.
  mysql_db:
          name: "{{ database_name }}"
          login_user: "{{ db_root_user }}"
          login_password: "{{ db_root_pass }}"
          state: present

- name: Creando usuario con privilegios en la base de datos.
  mysql_user:
          name: "{{ db_username }}"
          password: "{{ db_user_pass }}"
          priv: 'bdwordpress.*:ALL,GRANT'
          host: '%'
          login_user: "{{ db_root_user }}"
          login_password: "{{ db_root_pass }}"
          state: present

- name: Abrir puerto 3306 - UFW
  ufw:
    rule: allow
    port: "3306"

- name: Reiniciar firewall
  ufw:
          state: reloaded

