Vagrant.configure("2") do |config|
  config.vm.define "master2" do |master2|
    master2.vm.box = "debian/bookworm64"
    master2.vm.hostname = "Master2"
    master2.vm.network :private_network, ip: "192.168.10.55"
    master2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "Master2"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end
    master2.vm.provision "shell", path: "./debian.sh"
  end
end