---

- name: Instalar paquetes necesarios.
  yum:
    name: 
      - php
      - php-gd
      - php-xml
      - php-mbstring
      - php-mysqli
      - php-json
    state: present
  retries: 3
  delay: 10
  
- name: Reiniciar servicio web HTTP
  service:
    name: httpd
    state: restarted

- name: Descargar Wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
    mode: '0755'

- name: Establecer configuración de Wordpress
  template:
    src: "files/{{ ansible_os_family }}/wp-config.php"
    dest: "/var/www/html/wordpress/wp-config.php"
    owner: apache
    group: apache
    mode: '0644'

- name: Reiniciar servicio web HTTP
  service:
    name: httpd
    state: restarted


